# Generated by Django 3.2.7 on 2021-10-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Full_Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField(default=20)),
                ('Birthday', models.DateTimeField(verbose_name='Birthday')),
                ('Postman_Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Name', models.CharField(max_length=200)),
                ('Postal_code', models.CharField(max_length=200)),
                ('Post_longitude', models.CharField(max_length=200)),
                ('Post_latitude', models.CharField(max_length=200)),
                ('Post_city', models.CharField(max_length=200)),
                ('Post_current_Number', models.CharField(max_length=200)),
                ('Postman_working_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostApp.postman')),
            ],
        ),
    ]
